### ISSUE TITLE
还是加个防抖吧

### ISSUE THREAD

**Issue by oott123** [thewakingsands/xivdict#2]
![](https://user-images.githubusercontent.com/905663/140617356-fb02cf7f-c1a9-40c9-99a2-ea1f23c39108.gif)

不然对心脏不好

**Comment by Icemic** [comment]
参考这个交互 https://chrome.google.com/webstore/detail/%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/ikhdkkncnoglghljlkmcimlnlhkeamad?hl=zh-CN

**Comment by oott123** [comment]
> 
> 
> 参考这个交互 [chrome.google.com/webstore/detail/%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/ikhdkkncnoglghljlkmcimlnlhkeamad?hl=zh-CN](https://chrome.google.com/webstore/detail/%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/ikhdkkncnoglghljlkmcimlnlhkeamad?hl=zh-CN)

要按键感觉更复杂了，先解决可用性问题吧，感觉是 off-topic 了
